### ISSUE TITLE
http://nextbox.local not available from Chrome on Android

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#11]
I am trying to connect to http://nextbox.local from my mobile phone. My phone is connected to my local Wifi network, and to make sure I use it, I have de activated the mobile data from my carrier. I am able to access the nextbox.local local site from my computer, but from my phone I get:

DNS_PROBE_FINISHED_NXDOMAIN

Any idea why I have problems specifically on my phone? Anybody else able to replicate the issue?

**Comment by daringer** [comment]
The feature that allows an application/system to resolve http://nextbox.local to the correct IP address is called mDNS. 

As of today the chrome browser or generally Android does not support this, there are specific apps that show you services announced through mDNS like BonjourBrowser.

**Comment by jerabaul29** [comment]
Aaah, thanks for the explanation. Can this be added to the faq or manual or similar? Was thinking I was getting crazy at some point ^^ .

**Comment by daringer** [comment]
yup, added to the list: https://github.com/Nitrokey/nitrokey-documentation/issues/38
