### ISSUE TITLE
How to remove "visual clutter" on the top bar of the home menu?

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#12]
There is quite a bit of "visual clutter" on the top bar of the home menu: "Photos", "Activity", "Mails" etc. I have tried to remove these, but with no success. Any way to "personalize" the top bar and remove these to keep only documents and settings?

**Comment by daringer** [comment]
Generally this navigation is populated by the apps, so removing/disabling certain apps will remove the respective icons. But this might not be want you want. I am also not aware of a Nextcloud app that can configure this top navigation. The reason might also be quite simple: if you would hide an app icon there, then essentially the app is not accessible anymore, thus might also be disabled entirely.
