### ISSUE TITLE
Showing both how much space used and how much space left / free

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#13]
I can see on the bottom left corner how much space is used (for example: "10.4GB used"). It would be great to show this as "XX GB used of YYGB" or something like this, where the value XX is how many GBs (or any other unit) are in use currently, and the value YY is either the max value of the quota, or the free space left on the device (depending on which is more limited).

**Comment by daringer** [comment]
Do you mean the "xxGB used" information in the bottom left inside the "files" app?
This information is fully controlled by the nextcloud core app: "files" 
Such a feature request would need to go to: https://github.com/nextcloud/server we do not modify any apps or Nextcloud in general and provide a stock Nextcloud through docker.

Nevertheless inside the NextBox app we plan to introduce remaining space information in the overview, see this issue: https://github.com/Nitrokey/nextbox-app/issues/5
