### ISSUE TITLE
Allow the use of DNS based TLS form lets encrypt

### ISSUE THREAD

**Issue by fire** [Nitrokey/nextbox#14]
I was able to use dynamic dns, but the current implementation requires that nextbox be open to the web.

Using DNS based verification (via txt record) we can generate a certificate for a custom domain name.

**Comment by daringer** [comment]
Okok, understood, but low priority currently
will track it in `nextbox-daemon`: https://github.com/Nitrokey/nextbox-daemon/issues/20
