### ISSUE TITLE
cannot perform backup to USB key

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#16]
I have a USB key (model SanDisk; it is authentic, and works perfectly on all my laptops).

I try to perform a backup of the nextbox to the USB key. I follow the instructions at: https://docs.nitrokey.com/nextbox/backup-restore.html . I have formatted the whole USB disk as ext4 using the Ubuntu format tool. It displays as property: Filesystem type: ext3/ext4 .

However, I cannot perform backup to the USB key. 

- When I go to nextbox.local > NextBox App > Storage Management , I cannot see there the USB key; only the SD card and HDD
- Similarly, if I go to nextbox.local > NextBox App > Backup / Restore , I cannot see the USB key in the list of available devices (backup devices says 'list is empty').

I have tried to insert the USB key in different USB ports, no difference. The USB key works fine on my laptops.

Any idea what the problem is?

**Comment by daringer** [comment]
You should find it in "Storage Management", but the issue might be that the "whole usbstick" is formated as ext3 without first setting up a partition table and then formatting the first partition as ext4.

**Comment by jerabaul29** [comment]
Mmh, if it is not as straightforward as just formatting the USB key to ext in Ubuntu or similar (which is what a naive user like me expects when reading the documentation), can this be explained in more details on the documentation link posted above? :) .

**Comment by jerabaul29** [comment]
(for now all it says is "Make sure your storage device contains at least one partition formatted with a supported file-system (currently ext and xfs are supported).", which is the case for my USB thumb: one single ext partition).

**Comment by daringer** [comment]
usually it should be pretty straight forward, but it's hard to say why this particular one is not working, maybe also a power-supply issue? did you try it via a powered usb-hub? Happily updating the docs once we find out what's wrong here :)

**Comment by jerabaul29** [comment]
Yes, quite weird it did not work. These USB keys by themselves are quite reliable I think. I do not have an externally powered USB hub, but I have used this kind of USB keys with RPis many times before. Will dig into it...

**Comment by daringer** [comment]
cleaning up, feel free to re-open if still applicable
