### ISSUE TITLE
tool to perform automatic, incremental backup?

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#17]
Is there a way to perform automatic, incremental (or other kind of) backup? I have only found documentation about performing manual backup through the Nextbox App > Backup / Restore menu. Having a possibility to automatically backup regularly would be very useful :) .

**Comment by daringer** [comment]
currently not, as of now there is only a manual backup option.
See this issue: https://github.com/Nitrokey/nextbox-daemon/issues/24 
I expect for the next major release to have the first more advanced backup options in place

**Comment by jerabaul29** [comment]
A few thoughts:

- I do not think that this needs to be too "complicated", I guess some form of rsync agains the whole hard drive would be enough, right? :) .
- If there could be a simple script / option / hook / API / whatsoever else that would allow to perform such backup with rsync through ssh that would be perfect. For example what I want to do is to 1) have my nextbox home as it is now, 2) build a small RPi server and put it at the home of some family member, 3) automatically run a rsync-based backup over ssh on the RPi server, to backup the nextbox every night and keep a few snapshots (I can do the IT part of keeping / rotating the images :) ). My idea would be that would be great to have an official "recipe" on how to launch the rsync / with which base folder, so that we make sure that all is backed up :) .

**Comment by jerabaul29** [comment]
It looks like automatic peer to peer backup is now available natively in Nextcloud Hub II, right? Guess this should provide the solution needed?

https://nextcloud.com/blog/nextcloud-hub-2-brings-major-overhaul-introducing-nextcloud-office-p2p-backup-and-more/

**Comment by jerabaul29** [comment]
Looks like to get this we need nextcloud v23 and higher, see #33 . Any roadmap for making the NextBox app available on this version?

**Comment by daringer** [comment]
yes, are currently also targeting this new nextcloud app for backups in the near future, see #33  for more details

**Comment by tlaurion** [comment]
@daringer if LVM, I would suggest investigating and giving funds to wyng-backup
