### ISSUE TITLE
webserver is not owner of /var/www/html/custom_apps/nextbox

### ISSUE THREAD

**Issue by rootzoll** [Nitrokey/nextbox#18]
Hi. I after basic setup of the netbox (from store) I have this warning in the system settings:

![Bildschirmfoto 2021-09-10 um 00 57 33](https://user-images.githubusercontent.com/2472225/132773448-d2b61a8e-670e-462c-85fa-90498387dda0.png)

It doesnt look critical - if possible let me know how I can fix this. Thx.

**Comment by daringer** [comment]
Please check the FAQ: https://docs.nitrokey.com/nextbox/faq/nextcloud.html especially the 6th item

**Comment by rootzoll** [comment]
Ah OK got it - thanks :) Keep up the good work.
