### ISSUE TITLE
about the port forwarding

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#20]
From the get started help on port forwarding:

https://docs.nitrokey.com/nextbox/remote/port-forwarding.html

"
The port-forwarding and/or firewall rules have to be configured to allow traffic on ports 80 (HTTP-Server) and 443 (HTTPS-Server).
"

Honestly, this sounds scary to me to use as a setting on my home router. I am not sure if the machines of my other family members are set fully securely, and enabling port forwarding that may result in all machines to be exposed sounds scary. I was wondering: may it be actually safer to put the nextbox in the DMZ? This way the nextbox should be reachable for the dyndns, but all other machines on my network should still be as protected as before, right?

**Comment by jerabaul29** [comment]
So I guess my question is to some point: is it ok / safe / unsafe to put the nextbox in the DMZ, so that I do not need to allow port forwarding on my whole LAN?

**Comment by daringer** [comment]
oha, 
yeah this is clearly not optimally written (todo: https://github.com/Nitrokey/nitrokey-documentation/issues/38)...

the port-forwarding shall only be done for these to ports and ONLY towards the NextBox. In fact you always have to select a LAN-host to do the forwarding, anything else is not working. Any traffic will then only the forwarded from your router to your nextbox and back for both ports. This does not affect any other host/computer in your LAN. 

I would strongly recommend NOT to put the nextbox into a DMZ (which in my understanding means exposing the full host to the internet), setting up the port-forwarding is the cleanest & safest solution here.

**Comment by jerabaul29** [comment]
Ok, thanks a lot! :)

I am actually kind of a network semi n00b, so learning a lot by using the Nextbox :) . Think this is one more motivation for having extra good documentation as you plan - probably many people are in the same case as me and can 'hack' stuff but need some help with understanding the details :) . Many thanks for the explanation :) .

**Comment by jerabaul29** [comment]
This is working fine when set up correctly, so I think as you say that updating the documentation to make it "n00b friendly" would be perfect :) .

Feel free to close as far as I am concerned :) .
