### ISSUE TITLE
users and their passwords

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#21]
There are a few users set up on the nextbox from the start: root, nextuser, maybe some more. I was curious: can we get a list of all users that are set up, and their passwords (do they have default passwords?).

**Comment by daringer** [comment]
despite `nextuser` no other "real" user is set up. `root` is a default user, as many others which are set up by debian, by default. I would avoid documenting those, as this is debian stuff. Nevertheless this makes perfect sense to write down, that `nextuser` is created for the NextBox.

Further no default passwords are set, neither for `nextuser` nor for `root` to ensure that nobody can access the NextBox without setting a ssh-publickey inside the NextBox App.

That's all worth documenting, added a todo here: https://github.com/Nitrokey/nitrokey-documentation/issues/38

**Comment by jerabaul29** [comment]
Excellent, many thanks for the explanation and details :) Great to hear pre existing users have no default password which forces the use of SSH keys. Additional documentation about these points sound excellent :) .

**Comment by daringer** [comment]
done, https://docs.nitrokey.com/nextbox/faq/software.html
