### ISSUE TITLE
Updates: how does nextbox play with nextcloud?

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#22]
When going to:

```
nextbox.local/settings/admin/overview
```

I get the following:

```
Version

Nextcloud 21.0.0

A new version is available: Nextcloud 21.0.5
1 app has no update for this version available
Apps missing updates

    NextBox ↗
```

Does that mean that Nextcloud is ready to update but Nextbox is "getting in the way" by not being available for the newest Nextcloud version? Any risk this opens to running end of life / bugged / vulnerable Nextcloud services?

**Comment by daringer** [comment]
Nextcloud updates are rolled out by us, see here (3rd): https://docs.nitrokey.com/nextbox/faq/nextcloud.html
You can safely ignore the "missing app update for NextBox-App"-message, we roll the app out together with the `nextbox-daemon` thus it will always work with the currently Nextcloud.

Nextcloud versions are behind currently as there was a bug which kept us from updating https://github.com/nextcloud/server/issues/27575 ... it is fixed now, we're waiting for the next release, then likely we'll directly jump onto Nextcloud 22

**Comment by jerabaul29** [comment]
Sounds good, thanks for the details :) Wonder if this can be documented in more details / at another location than the faq :) .
