### ISSUE TITLE
TLS certificate acquisition with the DNS dynamic setup

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#23]
The documentation for the DNS dynamic setup:

https://docs.nitrokey.com/nextbox/remote/dynamic-dns.html

is quite detailed about the guided dynamic DNS setup with desec.io (I guess because the user needs to take some steps themselves, which forced explaining the steps etc), but the TLS / certificate acquisition system is quite obscure. Which certificate provider is being used (is it Let's Encrypt?)? Which acquisition mechanism is used (is it some form of Certbot or similar?)? How does the nitty gritty technical details are performed when the user click on the nextbox enable TLS button?

**Comment by jerabaul29** [comment]
(I think it may be worth to both explain this here, but also more importantly add some documentation on the dynamic-dns page :) ).

**Comment by daringer** [comment]
yap, clearly worth documenting, see todo here: https://github.com/Nitrokey/nitrokey-documentation/issues/38

in short:
* let's encrypt is the certificate issuer
* certbot is used without a plugin, just webroot 
* apache configuration is handled by nextbox-daemon
