### ISSUE TITLE
finding nextbox app and container version, checking if up to date, forcing update if needed

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#24]
Is there a way to check the nextbox app and container version, check that it is up to date, and force update if needed? I though I had found such a feature and setting, but I looked for it today and could not find it.

**Comment by daringer** [comment]
cleaning up, closing, please re-open if needed, generally see: https://docs.nitrokey.com/de/nextbox/faq/index.html to find answers to this

**Comment by keatonhj** [comment]
This needs re-opening because it doesn't work... my nextbox app is stuck at nextbox version 0.3 and it's because all nextcloud does is search here https://apps.nextcloud.com/apps/nextbox which is stuck on 0.3
