### ISSUE TITLE
"possible CSRF attack - connection will be closed"

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#28]
When updating the NextBox app, I got the following warning screen:

![Screenshot from 2021-10-16 21-00-11](https://user-images.githubusercontent.com/8382834/137599236-8a3a462f-9fac-4000-b2ed-c4c912e38cb4.png)

Clicking on reload the page took me to the update screen, and the update went just fine, so I think that all is good - just wanted to report, in case this is a "systematic" spurious warning :) .

Btw, I have a bit "special" config, explaining in another issue, will link back to it.

**Comment by jerabaul29** [comment]
May be related to #29 maybe?

**Comment by daringer** [comment]
They are recurring reports about this issue while upgrading, also in the Nextcloud boards, as long as it works after a retry, we'll consider this as not a real problem...
