### ISSUE TITLE
local access while enabled https but no port forwarding; why not working certificate?

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#29]
I set my nextbox to use https following the use of a reverse DNS (following the instructions on how to set it up deSEC). I did a few tests, and everything looked good. However, I had to turn off again the port forwarding on my router, so the access to the Nextbox through internet was disabled.

When accessing my nextbox through the local network now, I have to use https (logical, this has been enabled in the previous steps). However, for some reason, the certificate is not recognized as valid; any reason why? Any way to use https and valid certificate while accessing the box locally, with no port forwarding enabled?

**Comment by daringer** [comment]
the most recent update 1.0.14 should solve this for guided dns by changing the method the certificate is acquired...
