### ISSUE TITLE
"Talk" document keeps getting created

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#3]
In my "Files" tab, I have a "Talk" folder that keep coming back again and again every time I delete it. Any way to delete it once and for all?

**Comment by jerabaul29** [comment]
PS: not sure this is the right location, let me know if I should move to https://github.com/Nitrokey/nextbox-app/issues .

**Comment by daringer** [comment]
This likely is done by the "Talk" app, we do not really have the possibility to change this behavior.
You might try to disable the "Talk" app, if my assumption is right this should lead to the folder not being created anymore.

**Comment by jerabaul29** [comment]
Thanks, I went to the App tab and de-activated the Talk app, and indeed, the folder stopped popping up :) .
