### ISSUE TITLE
updating nextcloud or not?

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#33]
I would like to update nextcloud, but I get the message that:

"
Nextcloud 21.0.7

A new version is available: Nextcloud 22.2.3
1 app has no update for this version available
Apps missing updates
    NextBox
"

(see screenshot).

Does that mean that I can update NextCloud and that the old NetxBox app will be used, or does that mean that if I try to update NextCloud, NextBox and stuff around it will stop working? Can you push some updated NextBox app? :) .

![Screenshot from 2021-12-22 18-36-06](https://user-images.githubusercontent.com/8382834/147133460-6c4ba034-73a3-4caf-bb96-ad9e910ecaf1.png)

**Comment by jerabaul29** [comment]
PS: the reason why I am very keen on this update is that:

- the current NextCloud version I run (21) is likely soon out of support I am afraid from the NextCloud webpage, as it is the next one to be discontinued,
- the 22.3 (which I guess I can install after bumping to 22.2?) gives an additional function that I really want before I can go from "casual, test case" use to "true full scale use" home, i.e., adding "📦 Nextcloud Backup: a peer-to-peer backup solution designed for private users" (see screenshot).

![Screenshot from 2021-12-22 18-41-08](https://user-images.githubusercontent.com/8382834/147135577-6562f22a-2b37-4602-bfdc-b663cc61fbf5.png)

**Comment by daringer** [comment]
generally it is not possible/intended to update nextcloud on your own, see: https://docs.nitrokey.com/nextbox/faq/nextcloud.html (3rd point)

Currently we roughly plan to release NC 22 until end of January to be sure to not hit EOL for NC 21 as defined here:
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

Shortly after that (~1-2months), we want to to jump to NC 23 to then finally be "on-track" again after a Nextcloud bug kept us from updating NC versions for roughly 6(?) months...

**Comment by jerabaul29** [comment]
Thanks for the explanation. Could there be some roadmap / 'explanation of current project status to users' some place so that people know what is going on / what to expect etc? :) Good luck with the update, very much looking forward to these :) .

**Comment by daringer** [comment]
> Could there be some roadmap / 'explanation of current project status to users' some place so that people know what is going on / what to expect etc?

Yes, we also see the need, currently in discussion how this might be done.
