### ISSUE TITLE
Thinking about what the scope of Nextbox is - add infrastructure to make it easy to use some additional functionalities: example easy TURN server for talk?

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#35]
This will start with a bit of "meta" discussion: what is the goal of Nextbox? I understand it aims at being "a safe home for your data", but why stop there when it is basically an easy way to run Nextcloud on a RPi4? :) . For example, Nextbox helps with a lot of the technicalities needed to make a self hosted Nextcloud file storage available through https from anywhere in the world by helping with the dynDNS thing, but what about other core functionalities of Nextcloud like Talk or Collabora, that are also core of the Nextcloud value offering?

Said otherwise, my point is: why not go further and help bring some more key Nextcloud functionalities to the user? For me, the next "key functionalities" to think about could be i) some form of online call app (i.e., the "Talk" app), and some form of online document editing (i.e. Collabora). I understand that ARM support with Collabora is fairly new and that some details are still being ironed out, so maybe good to take Talk as the first next step (I will do so in this discussion :) ).

I have installed Talk on my Nextbox, and it works like a charm on the local network. However, it does not work calling from outside the local network. This is expected as described here: https://nextcloud-talk.readthedocs.io/en/latest/TURN/ . I would need a TURN server running and set up, such as coTURN. Of course, I can ssh into my Nextbox and set it up myself, but I was wondering: there are certainly many more users who would like to use Talk, would it be possible that this is supported by the Nextbox out of the box? I.e., "set up things" (how is open to discussion of course :) ), so that the user can just tick in a button and have the "coTURN for Talk" server up and running would be great. Do you think that this would be doable, by either adding the coTURN server directly in the Nextbox docker container, or allowing starting it in a new container with shared network stack or something like this?

**Comment by daringer** [comment]
although a valid topic, we at this point don't want to (are not able to) introduce major new packages/containers into the OS. 

> why not go further and help bring some more key Nextcloud functionalities to the user?

Because each introduced functionality is another package/dependency to maintain/test/verify functionality at. Fully understand that this would make sense, but the scope of the product would considerably increase once we open this door.
