### ISSUE TITLE
Enable HTTPS fails with email missing error, even when email address provided

### ISSUE THREAD

**Issue by msgitter** [Nitrokey/nextbox#61]
All 4 checks were green, and I provided an email address.
Then I pressed `Enable HTTPS`.

I then got error message, saying that HTTPS could not be enabled:
`Failed setting up HTTPS/TLS, domain and/or e-mail missing.`

In /srv/varlog/nextbox.log I saw:
`cannot enable tls, domain: 'mydomain.com' email: 'None'`

Manual workaround by adding email address manually to config:
```
sudo vi /srv/nextbox/nextbox.conf
# reboot
sudo halt
```
Afterwards I could Enable HTTPS successfully.

NextBox Daemon Version: 1.0.22-1

Using: Static DNS Configuration
I also tried before all checks become green, in case that makes a difference.

**Comment by daringer** [comment]
thanks for reporting, we're looking into it...
