### ISSUE TITLE
where can I buy the RPi4 case you use?

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#65]
I am very happy with the RPi4 case of my nextbox - it seems to provide good cooling, it is compact, and generally working well. I would be interested in buying some extra of these cases, to host some RPi 4s I will use on some other projects home. Is the case you use possible to buy somewhere? :) .

**Comment by daringer** [comment]
we have (proudly) designed and optimized the casing ourselves and also partnering with another company to produce them, you will not find them in the wild. Nevertheless, you can write to shop (at) nitrokey (dot) com and ask there, I think it should be possible to sell you just the casing...

**Comment by jerabaul29** [comment]
Nice :) . Ok, thanks!
