### ISSUE TITLE
Old Docker Images should be cleaned up

### ISSUE THREAD

**Issue by nestire** [Nitrokey/nextbox#70]
After every Update the old Docker images should be cleaned up because otherwise they just taking up space and don't do anything 

> root@nextbox:/srv# docker images                                                                                                                                                                     
> REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> nextcloud           23.0.6-apache       99b4a5a405fe        4 days ago          902MB
> nextcloud           23.0.5-apache       e202fe83dea3        6 weeks ago         902MB
> nextcloud           21.0.7-apache       85fdfdcf408d        6 months ago        866MB
> nextcloud           22.2.3-apache       01e4249c017d        7 months ago        882MB
> nextcloud           21.0.0-apache       3d06f2d17193        15 months ago       780MB
> mariadb             10.5.9              939d05495a90        16 months ago       387MB
> redis               5.0.11-alpine       f84d97cdcb59        16 months ago       29.3MB

**Comment by keatonhj** [comment]
has this been fixed yet? seems like this would cause the system to get worse and worse over time.
