### ISSUE TITLE
Question:  how to enable https for  "nextbox.local" ?

### ISSUE THREAD

**Issue by torstello** [Nitrokey/nextbox#71]
Hi there,
for the initial setup of my new nextbox I want to sync / upload my files  + photos + documents in the local (http) network;
not over the internet (https) link.

I thought to use the nexcloud (sync)  app (on my macbook) but this doesn't work b/c for the app it is mandatory to provide a https url.  Just typing "http://nexbox.local" results in an ssl error b/c the url is automatically re-written to https://....

I could of course just use the local webapp and upload, but this is quite inconvenient.

so, what would you suggest in this case?

could I enable https for the nextbox.local instance (via self-signed cert) ?

**Comment by daringer** [comment]
hey hey,

no this is currently not possible, self-signed might be somehow possible to enforce, but is currently not supported. We recommend using the guided dns approach, please also see the documentation about remote access here: https://docs.nitrokey.com/nextbox/remote/
