### ISSUE TITLE
periodically re-index all files

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#74]
I encounter quite often the situation where the index is out of date (for example, because a direct upload took place to a user data folder some way or another).

Would it be possible to periodically run the ```occ``` command "the right way" (I understand the right user and docker container has to be used, and I do not feel 100% confident I would get it right myself), automatically, to make sure these issues get ironed out after some while? Could be once a week for example, in the middle of the (local) night?

I think the correct command should be a mix of the answers at:

https://help.nextcloud.com/t/solved-ncp-how-to-run-occ-command/101453

https://help.nextcloud.com/t/run-occ-files-scan-all-automatically-in-docker-container/100429/5

If you could in the first time confirm what the exact command line command should be issued to do this right with the right docker and user parameters, that would be very helpful :) .

**Comment by jans23** [comment]
> direct upload took place to a user data folder

Do you mean via SSH?

**Comment by jerabaul29** [comment]
Yes. The issue I have found is that trying to upload more than a couple of images at a time through the android app fails, so I have ended up ssh-ing / scp-ing directly to the nextbox to upload for example a few GBs of images at a time when I or some of my user come to me with a "big" archive of images they want to keep on the nextbox I administrate.

**Comment by jans23** [comment]
We don't support uploading files via SSH thus may not help here.

**Comment by jerabaul29** [comment]
I understand, and I do not like uploading through ssh either, it is a hazzle for me and my users. But to be honest, I do not see an alternative at the moment. One of my user wanted to upload like 500MB of pictures the other day, and I spent a couple of hours trying to get these uploaded through the android app without success - somehow the first couple of pictures were uploading, and then it stopped uploading. Very frustrating, this makes the nextbox in practice unusable for several of my users who have the issue, so the scp-ing workaround is something I have to do, otherwise the nextbox is unusable.

Not sure if this is an issue with the android or the server side, but it seems this is a known issue: see for example https://www.reddit.com/r/NextCloud/comments/php0n6/android_app_is_really_sluggish/ https://github.com/nextcloud/android/issues/3692 https://news.ycombinator.com/item?id=18648023 

Just to say, I agree ssh/scp-ing is not the optimal solution, but at the moment, this is the only thing that I manage to get to work to upload large amounts of pictures to the nextbox in a reliable way. The only missing step is forcing to index these pictures that are copied in the /srv/nextcloud/data/username/Photos/SOME_FOLDER location, and then I can provide a fully usable solution to my users :) . (in particular, viewing pictures once they are indexed works well through the android app).
