### ISSUE TITLE
Debug logs flood

### ISSUE THREAD

**Issue by fouvry** [Nitrokey/nextbox#76]
I get tons of log messages about /appinfo/app.php being deprecated (I cannot copy the full message, because they run past so fast).
I turned off debug logging (I'm not aware of having turned that on), and then the flood stopped.
Is this an issue that is being worked on?  What should the log level be set to?

Thank you!

A sample:
``{"reqId":"6py0ATkCdGoYtqWD5bsI","level":0,"time":"2023-06-24T11:57:45+00:00","remoteAddr":"XXX","user":"XXX","app":"nextbox","method":"DELETE","url":"/apps/files/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0","version":"25.0.4.1","data":{"app":"nextbox"},"id":"XXX"}``

**Comment by daringer** [comment]
fixed in 0f9702ad7f54dee538983413db55c41fd0143aae - stable release expected this week
