### ISSUE TITLE
Be able to log in as several users and switch between them

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#8]
For now it looks like, when clicking on the "user" icon on the top right corner, I can only "log out" and later on "log in" to access the nextcloud as another user. Would it be possible to add options "a la gmail", to:

- "add extra user account": be able to log in as several users without the need to log in and out all the time
- "select which account to work from": to be able to switch between different logged in accounts.

**Comment by daringer** [comment]
User Management is not in our hands this is purely in Nextcloud's scope. 
I am also not aware if such a feature exists for Nextcloud.

**Comment by jans23** [comment]
https://apps.nextcloud.com/apps/impersonate
