### ISSUE TITLE
2 factor authentication

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#9]
Would it be possible to make 2FA available out of the box? For now, I went to:

https://docs.nextcloud.com/server/21/admin_manual/configuration_user/two_factor-auth.html

And installed the TOTP app "Two-Factor TOTP Provider, by Christoph Wurst AGPL-licensed". Would it be possible that this app or a similar one be installed out of the box?

Would it also be possible to have an app to allow 2FA with nitrokeys? :) .

**Comment by jerabaul29** [comment]
edit: I think the app in question is nitrokey-compatible :) .

**Comment by daringer** [comment]
So far I know 2FA is available out-of-the box as you saw, you just need a 2FA provider.

Furthermore, maybe more interesting is "Settings" -> "Personal" -> "Security" , once https in activated you can set up Passwordless Authentification using a Nitrokey FIDO2 device to log in.

> And installed the TOTP app "Two-Factor TOTP Provider, by Christoph Wurst AGPL-licensed". Would it be possible that this app or a similar one be installed out of the box?

Currently we follow the guideline to not modify Nextcloud setup process despite providing the NextBox App, this might change in the future, then a 2FA provider would be one of the top candidates.

**Comment by jans23** [comment]
Technically you have to choose between TOTP and FIDO. For FIDO see https://apps.nextcloud.com/apps/twofactor_u2f
